### ISSUE TITLE
clearmash API should support searching

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-back#116]
#### reproduction steps
* try to use the clearmash search api: https://bh.clearmash.com/API/V5/Services/Search.svc

##### expected
* api should work or provide a different api for searching

##### actual
* returns error:
```
An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.InvalidOperationException: An exception was thrown in a call to a WSDL export extension: System.ServiceModel.Description.DataContractSerializerOperationBehavior
 contract: http://www.clearmash.com/api/v5/services:ISearch ----> System.Runtime.Serialization.InvalidDataContractException: Type 'ClearMash.ServerAPI.V5.DataContracts.Search.SearchDatasourceField' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute.  If the type is a collection, consider marking it with the CollectionDataContractAttribute.  See the Microsoft .NET Framework documentation for other supported types.
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContractSet.GetDataContract(Type clrType)
   at System.Runtime.Serialization.DataContractSet.AddCollectionDataContract(CollectionDataContract collectionDataContract)
   at System.Runtime.Serialization.DataContractSet.InternalAdd(XmlQualifiedName name, DataContract dataContract)
   at System.Runtime.Serialization.DataContractSet.AddClassDataContract(ClassDataContract classDataContract)
   at System.Runtime.Serialization.DataContractSet.InternalAdd(XmlQualifiedName name, DataContract dataContract)
   at System.Runtime.Serialization.DataContractSet.Add(Type type)
   at System.Runtime.Serialization.XsdDataContractExporter.Export(Type type)
   at System.ServiceModel.Description.MessageContractExporter.ExportType(Type type, String partName, String operationName, XmlSchemaType& xsdType)
   at System.ServiceModel.Description.DataContractSerializerMessageContractExporter.ExportBody(Int32 messageIndex, Object state)
   at System.ServiceModel.Description.MessageContractExporter.ExportMessage(Int32 messageIndex, Object state)
   at System.ServiceModel.Description.MessageContractExporter.ExportMessageContract()
   at System.ServiceModel.Description.WsdlExporter.CallExtension(WsdlContractConversionContext contractContext, IWsdlExportExtension extension)
   --- End of inner ExceptionDetail stack trace ---
   at System.ServiceModel.Description.ServiceMetadataBehavior.MetadataExtensionInitializer.GenerateMetadata()
   at System.ServiceModel.Description.ServiceMetadataExtension.EnsureInitialized()
   at System.ServiceModel.Description.ServiceMetadataExtension.HttpGetImpl.InitializationData.InitializeFrom(ServiceMetadataExtension extension)
   at System.ServiceModel.Description.ServiceMetadataExtension.HttpGetImpl.GetInitData()
   at System.ServiceModel.Description.ServiceMetadataExtension.HttpGetImpl.TryHandleDocumentationRequest(Message httpGetRequest, String[] queries, Message& replyMessage)
   at System.ServiceModel.Description.ServiceMetadataExtension.HttpGetImpl.ProcessHttpRequest(Message httpGetRequest)
   at SyncInvokeGet(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
```

**Comment by OriHoch** [comment]
notified Clearmash about this bug, waiting acknowledgement and ETA for fix

**Comment by omrisuissa** [comment]
We aware of the problem.
A fix will be entered in the next update.
We are waiting for Haim to fix a "logical data corruption" in BHP so we can re-run the data migration with the new version (that includes this fix).
**Current ETA (assuming Haim will fix it until Tuesday): one week - Thursday (09/03/2017).**

**Comment by OriHoch** [comment]
thanks @omrisuissa !

**Comment by OriHoch** [comment]
@nuritgazit @daonb 
following conversation with @omrisuissa - this is the problem as I understand it - 

Beit Hatfutsot have some business rules about the data, for example - a certain field should be unique, or a field is related to another field etc..
Beit Hatfutsot Clearmash templates adhere to these business rules - as specified by Beit Hatfutsot
So far so good
The problem is that the old BHP database didn't enforce these rules (or didn't enforce them properly) -
This means that when we try to import the data into Clearmash it rejects it because it doesn't adhere to the rules.

I think that this problem will not be solved so easily (fixing the data to adhere to the rules) - so I suggest to change the rules a bit on Clearmash to allow importing the data as-is
Later we can always fix the data on Clearmash and enforce the proper rules

**Comment by nuritgazit** [comment]
@OriHoch Generally speaking, sounds good. What does it mean exactly "to change the rules a bit"?

**Comment by OriHoch** [comment]
@nuritgazit edit the relevant clearmash template - 
I'm not familiar with it but I understand it's an XML file which contains all the definitions like relation between fields / validation rules etc..

**Comment by nuritgazit** [comment]
@OriHoch It's the file Haim created?

**Comment by omrivm** [comment]
This is a discussion about data quality vs time to market. 

There is not right or wrong here and we will do whatever you think is right (my personal opinion is that if data quality can be achieved in reasonable time it is better, but this is not my decision, but yours).

Since, from my understanding, Haim is the owner of the data I think this is a discussion you need to conduct with him.

Please update on your decision and we will adjust accordingly.

**Comment by OriHoch** [comment]
I agree, the question is what is a reasonable time and what is the expected/estimated time

**Comment by nuritgazit** [comment]
who answers these questions?

**Comment by omrisuissa** [comment]
Hi,
We have updated the environment with the new version. Please verify that this issue is fixed.
Your users and api tokens has been reset, so you need to contact Chen to get your new users.
Omri

**Comment by OriHoch** [comment]
Amazing! thanks @omrisuissa I'll have a look tomorrow

**Comment by OriHoch** [comment]
looks good, thank @omrisuissa
